### ISSUE TITLE
[WORKAROUND] Libraw not installed / wrong version

### ISSUE THREAD

**Issue by dschiller** [mateusz-michalik/cr2-to-jpg#4]
```
Traceback (most recent call last):
  File "D:\Work\Photogrammetry Scans\ConvertCR2toJPG.py", line 64, in <module>
    convert_cr2_to_jpg(raw_images)
  File "D:\Work\Photogrammetry Scans\ConvertCR2toJPG.py", line 39, in convert_cr2_to_jpg
    raw_image_process = raw.Raw(raw_image)
  File "C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\rawkit\raw.py", line 70, in __init__
    self.libraw = LibRaw()
  File "C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\libraw\bindings.py", line 39, in __init__
    raise ImportError('Cannot find LibRaw on your system!')
ImportError: Cannot find LibRaw on your system!
```

I copied `https://www.libraw.org/download/LibRaw-0.20.0-Win64.zip` Content to `C:\Tools\LibRaw-0.20.0`. Added `C:\Tools\LibRaw-0.20.0\bin` to Environment `path` Variable. Exectued the Convert Python Script and it still fails. I also tried to copy the `libraw.dll` to the same folder of the Python Script. Still fails.

# Edit

Renamed `C:\Tools\LibRaw-0.20.0\bin\libraw.dll` to `C:\Tools\LibRaw-0.20.0\bin\raw.dll` and now the Version seems to be wrong.

```
D:\Work\Photogrammetry Scans>ConvertCR2toJPG.py -s "Mushroom Toy" -d "Mushroom Toy"
Converting the following raw image: Mushroom Toy\IMG_1285.CR2 to JPG
Traceback (most recent call last):
  File "C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\libraw\bindings.py", line 46, in __init__
    }[self.version_number[1]]
KeyError: 20

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Work\Photogrammetry Scans\ConvertCR2toJPG.py", line 64, in <module>
    convert_cr2_to_jpg(raw_images)
  File "D:\Work\Photogrammetry Scans\ConvertCR2toJPG.py", line 39, in convert_cr2_to_jpg
    raw_image_process = raw.Raw(raw_image)
  File "C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\rawkit\raw.py", line 70, in __init__
    self.libraw = LibRaw()
  File "C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\libraw\bindings.py", line 49, in __init__
    'Unsupported Libraw version: %s.%s.%s.' % self.version_number
ImportError: Unsupported Libraw version: 0.20.0.
```

Also tried `LibRaw-0.19.5`. Same Issue. Not supported.

# Edit

Added Version `19` and `20` structs to `C:\Users\ds\AppData\Roaming\Python\Python37\site-packages\libraw\bindings.py`.

![image](https://user-images.githubusercontent.com/3144986/95562707-cecf8280-0a1c-11eb-895a-6df0c1da8a27.png)

**Comment by mateusz-michalik** [comment]
@dschiller, is there anything that needs to be done here on my end? Admittedly, I did not test on Windows as I had just put this together for myself for personal use and I'm on OSX.

**Comment by dschiller** [comment]
HeyMateusz, as long the workaround worksnoneed on your side. Thanks a lot!
